# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_aboutDialog(object):
    def setupUi(self, aboutDialog):
        aboutDialog.setObjectName("aboutDialog")
        aboutDialog.resize(489, 328)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        aboutDialog.setFont(font)
        self.aboutLabel = QtWidgets.QLabel(parent=aboutDialog)
        self.aboutLabel.setGeometry(QtCore.QRect(110, 10, 361, 261))
        self.aboutLabel.setObjectName("aboutLabel")
        self.aboutOkButton = QtWidgets.QPushButton(parent=aboutDialog)
        self.aboutOkButton.setGeometry(QtCore.QRect(220, 270, 89, 25))
        self.aboutOkButton.setObjectName("aboutOkButton")
        self.label = QtWidgets.QLabel(parent=aboutDialog)
        self.label.setGeometry(QtCore.QRect(20, 30, 81, 91))
        self.label.setObjectName("label")

        self.retranslateUi(aboutDialog)
        QtCore.QMetaObject.connectSlotsByName(aboutDialog)

    def retranslateUi(self, aboutDialog):
        _translate = QtCore.QCoreApplication.translate
        aboutDialog.setWindowTitle(_translate("aboutDialog", "About"))
        self.aboutLabel.setText(_translate("aboutDialog", "<h3><span style=\" font-size:large; font-weight:700;\">Youtube Downloader</span></h3><p><span style=\" font-weight:700;\">Phiên bản:</span> 0.4.10</p><p><span style=\" font-weight:700;\">Năm: </span>2023-2025</p><p><span style=\" font-weight:700;\">Giấy phép: </span>MIT </p><p><span style=\" font-weight:700;\">Github: </span><a href=\"https://github.com/x1-2023/yt-channel-downloader\"><span style=\" text-decoration: underline; color:#0000ff;\">Xem trên Github</span></a></p><p><span style=\" font-weight:700;\">Tác giả: </span><a href=\"mailto:info@quicknode.net\"><span style=\" text-decoration: underline; color:#0000ff;\">info@quicknode.net</span></a></p>"))
        self.aboutOkButton.setText(_translate("aboutDialog", "Đóng"))
        self.label.setText(_translate("aboutDialog", "<html><head/><body><p><img src=\":/images/icon.png\" width=\"64\" height=\"64\"/></p></body></html>\n"
""))
